{% set version = "1.1-6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-maptools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/maptools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/maptools/maptools_{{ version }}.tar.gz
  sha256: d6a5df52db03b2231f21921b693c67f85df3c3b376181aa13ef4f21710f69308

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-foreign                  # [build_platform != target_platform]
    - r-sp                       # [build_platform != target_platform]
    - r-lattice                  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-foreign >=0.8
    - r-lattice
    - r-sp >=1.0_11
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-foreign >=0.8
    - r-lattice
    - r-sp >=1.0_11

test:
  commands:
    - $R -e "library('maptools')"           # [not win]
    - "\"%R%\" -e \"library('maptools')\""  # [win]

about:
  home: http://r-forge.r-project.org/projects/maptools/
  license: GPL-2.0-or-later
  summary: Set of tools for manipulating geographic data. It includes binary access to 'GSHHG' shoreline files. The package also provides interface wrappers for exchanging spatial objects with packages such as 'PBSmapping', 'spatstat', 'maps', 'RArcInfo', and others.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: maptools
# Version: 0.9-5
# Date: 2019-02-18
# Title: Tools for Handling Spatial Objects
# Authors@R: c( person("Roger", "Bivand", role = c("cre", "aut"), email = "Roger.Bivand@nhh.no", comment=c(ORCID="0000-0003-2392-6140")), person("Nicholas", "Lewin-Koh", role = "aut"), person("Edzer", "Pebesma", role = "ctb"), person("Eric", "Archer", role = "ctb"), person("Adrian", "Baddeley", role = "ctb"), person("Nick", "Bearman", role = "ctb"), person("Hans-Jorg", "Bibiko", role = "ctb"), person("Steven", "Brey", role = "ctb"), person("Jonathan", "Callahan", role = "ctb"), person("German", "Carrillo", role = "ctb"), person("Stephane", "Dray", role = "ctb"), person("David", "Forrest", role = "ctb"), person("Michael", "Friendly", role = "ctb"), person("Patrick", "Giraudoux", role = "ctb"), person("Duncan", "Golicher", role = "ctb"), person("Virgilio", "Gomez Rubio", role = "ctb"), person("Patrick", "Hausmann", role = "ctb"), person("Karl Ove", "Hufthammer", role = "ctb"), person("Thomas", "Jagger", role = "ctb"), person("Kent", "Johnson", role = "ctb"), person("Sebastian", "Luque", role = "ctb"), person("Don", "MacQueen", role = "ctb"), person("Andrew", "Niccolai", role = "ctb"), person("Edzer", "Pebesma", role = "ctb"), person("Oscar", "Perpinan Lamigueiro", role = "ctb"), person("Ethan", "Plunkett", role = "ctb"), person("Tom", "Short", role = "ctb"), person("Greg", "Snow", role = "ctb"), person("Ben", "Stabler", role = "ctb"), person("Murray", "Stokely", role = "ctb"), person("Rolf", "Turner", role = "ctb"))
# Encoding: UTF-8
# Depends: R (>= 2.10), sp (>= 1.0-11)
# Imports: foreign (>= 0.8), methods, grid, lattice, stats, utils, grDevices
# Suggests: rgeos (>= 0.1-8), spatstat (>= 1.50), PBSmapping, maps, RColorBrewer, raster, polyclip, spatstat.utils
# Enhances: gpclib, RArcInfo
# Description: Set of tools for manipulating geographic data. It includes binary access to 'GSHHG' shoreline files. The package also provides interface wrappers for exchanging spatial objects with packages such as 'PBSmapping', 'spatstat', 'maps', 'RArcInfo', and others.
# License: GPL (>= 2)
# URL: http://r-forge.r-project.org/projects/maptools/
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-02-18 08:37:28 UTC; rsb
# Author: Roger Bivand [cre, aut] (<https://orcid.org/0000-0003-2392-6140>), Nicholas Lewin-Koh [aut], Edzer Pebesma [ctb], Eric Archer [ctb], Adrian Baddeley [ctb], Nick Bearman [ctb], Hans-Jorg Bibiko [ctb], Steven Brey [ctb], Jonathan Callahan [ctb], German Carrillo [ctb], Stephane Dray [ctb], David Forrest [ctb], Michael Friendly [ctb], Patrick Giraudoux [ctb], Duncan Golicher [ctb], Virgilio Gomez Rubio [ctb], Patrick Hausmann [ctb], Karl Ove Hufthammer [ctb], Thomas Jagger [ctb], Kent Johnson [ctb], Sebastian Luque [ctb], Don MacQueen [ctb], Andrew Niccolai [ctb], Edzer Pebesma [ctb], Oscar Perpinan Lamigueiro [ctb], Ethan Plunkett [ctb], Tom Short [ctb], Greg Snow [ctb], Ben Stabler [ctb], Murray Stokely [ctb], Rolf Turner [ctb]
# Maintainer: Roger Bivand <Roger.Bivand@nhh.no>
# Repository: CRAN
# Date/Publication: 2019-02-18 10:50:07 UTC
